include data ops step

diff --git a/.gitlab/ci_cd.yaml b/.gitlab/ci_cd.yaml
--- a/.gitlab/ci_cd.yaml
+++ b/.gitlab/ci_cd.yaml
@@ -139,6 +139,20 @@ variables:
       ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${AUTHOR}"
       tb --host $TB_HOST --token $TB_ADMIN_TOKEN env use $ENVIRONMENT_NAME
 
+    # Custom test data operations
+    - |
+    DATAOPS_FILE=./deploy/${VERSION}/dataops.sh
+      if [ -f "$DATAOPS_FILE" ]; then
+        if ! [ -x "$DATAOPS_FILE" ]; then
+          echo "Error: You do not have permission to execute '$DATAOPS_FILE'. Run:"
+          echo "> chmod +x $DATAOPS_FILE"
+          echo "and commit your changes"
+          exit 1
+        else
+          $DATAOPS_FILE
+        fi
+      fi
+
     - |
       if [ -f ./scripts/exec_test.sh ]; then
         ./scripts/exec_test.sh
