Update gitlab

diff --git a/.gitlab/ci_cd.yaml b/.gitlab/ci_cd.yaml
--- a/.gitlab/ci_cd.yaml
+++ b/.gitlab/ci_cd.yaml
@@ -17,7 +17,7 @@ variables:
       echo "Go to the tokens section in your Workspace, copy the 'admin token' and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1;
     fi
 
-.run_ci:
+.deploy_ci:
   stage: ci
   image: ${IMAGE_BASE}
   interruptible: true
@@ -78,10 +78,10 @@ variables:
 
     # Deploy changes to the test Environment
     - |
-      CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
-      if [ ! -f "$CI_DEPLOY_FILE" ]; then
+      DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+      if [ ! -f "$DEPLOY_FILE" ]; then
         if [ "$TB_DEPLOY" = "true" ]; then
-          tb --semver ${VERSION} deploy --fixtures --populate --wait --v3 ${CI_FLAGS}
+          tb --semver ${VERSION} deploy --v3 ${CI_FLAGS}
           tb release ls
         else
           tb deploy --populate --fixtures --wait
@@ -90,15 +90,15 @@ variables:
 
     # Custom deployment to the test Environment
     - |
-      CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
-      if [ -f "$CI_DEPLOY_FILE" ]; then
-        if ! [ -x "$CI_DEPLOY_FILE" ]; then
-          echo "Error: You do not have permission to execute '$CI_DEPLOY_FILE'. Run:"
-          echo "> chmod +x $CI_DEPLOY_FILE"
+      DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+      if [ -f "$DEPLOY_FILE" ]; then
+        if ! [ -x "$DEPLOY_FILE" ]; then
+          echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
+          echo "> chmod +x $DEPLOY_FILE"
           echo "and commit your changes"
           exit 1
         else
-          $CI_DEPLOY_FILE
+          $DEPLOY_FILE
         fi
       fi
 
@@ -126,7 +126,68 @@ variables:
           ${BASE_CMD} coverage --wait ${LABELS_CMD}
       fi
 
-.run_cd:
+.test:
+  stage: ci
+  image: ${IMAGE_BASE}
+  interruptible: true
+  before_script:
+    - apt-get update && apt-get install -y --no-install-recommends git
+  script:
+    - *validate_input
+    - _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
+    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR
+    - _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
+    - source .tinyenv
+
+    # Create Python Virtual Environment
+    - python -m venv .venv
+    - source .venv/bin/activate
+
+    # Install Tinybird CLI
+    - |
+      if [ -f "requirements.txt" ]; then
+        pip install -r requirements.txt
+      else
+        pip install tinybird-cli
+      fi
+
+    # Tinybird version
+    - tb --version
+
+    # Check auth
+    - tb --host $TB_HOST --token $TB_ADMIN_TOKEN auth info
+
+    # Use CI environment
+    - |
+      AUTHOR=$(echo "$CI_COMMIT_AUTHOR" | sed -E 's/[^a-zA-Z0-9]//g')
+      ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${AUTHOR}"
+      tb --host $TB_HOST --token $TB_ADMIN_TOKEN env use $ENVIRONMENT_NAME
+
+    - |
+      if [ -f ./scripts/exec_test.sh ]; then
+        ./scripts/exec_test.sh
+      fi
+
+    # Run data quality tests
+    - tb test run -v -c 4
+
+    # Run pipe regression tests
+    - echo ${CI_MERGE_REQUEST_LABELS}
+    - REGRESSION_LABELS=$(echo "${CI_MERGE_REQUEST_LABELS}" | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /^--/) print $i}' ORS=',' | sed 's/,$//')
+    - echo ${REGRESSION_LABELS}
+    - |
+      CONFIG_FILE=./tests/regression.yaml
+      BASE_CMD="tb env regression-tests"
+      LABELS_CMD="$(echo ${REGRESSION_LABELS} | tr , ' ')"
+      if [ -f ${CONFIG_FILE} ]; then
+          echo "Config file found: ${CONFIG_FILE}"
+          ${BASE_CMD} -f ${CONFIG_FILE} --wait ${LABELS_CMD}
+      else
+          echo "Config file not found at '${CONFIG_FILE}', running with default values"
+          ${BASE_CMD} coverage --wait ${LABELS_CMD}
+      fi
+
+.deploy_main:
   stage: cd
   image: ${IMAGE_BASE}
   interruptible: true
@@ -162,8 +223,8 @@ variables:
 
     # Deploy changes to the main Workspace
     - |
-      CD_DEPLOY_FILE=./deploy/${VERSION}/cd-deploy.sh
-      if [ ! -f "$CD_DEPLOY_FILE" ]; then
+      DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+      if [ ! -f "$DEPLOY_FILE" ]; then
         if [ "$TB_DEPLOY" = "true" ]; then
           tb --semver ${VERSION} deploy --v3 ${CD_FLAGS}
           tb release ls
@@ -174,15 +235,15 @@ variables:
 
     # OPTIONALLY Custom deployment to main Workspace. Useful for post CD deploy commands (e.g.: tb pipe populate)
     - |
-      CD_DEPLOY_FILE=./deploy/${VERSION}/cd-deploy.sh
-      if [ -f "$CD_DEPLOY_FILE" ]; then
-        if ! [ -x "$CD_DEPLOY_FILE" ]; then
-          echo "Error: You do not have permission to execute '$CD_DEPLOY_FILE'. Run:"
-          echo "> chmod +x $CD_DEPLOY_FILE"
+      DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+      if [ -f "$DEPLOY_FILE" ]; then
+        if ! [ -x "$DEPLOY_FILE" ]; then
+          echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
+          echo "> chmod +x $DEPLOY_FILE"
           echo "and commit your changes"
           exit 1
         else
-          $CD_DEPLOY_FILE
+          $DEPLOY_FILE
         fi
       fi
 
