add post deploy script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -172,6 +172,20 @@ jobs:
           ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"
           tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env use $ENVIRONMENT_NAME
 
+      - name: Post deploy
+        run: |
+          POSTDEPLOY_FILE=./deploy/${VERSION}/postdeploy.sh
+          if [ -f "$POSTDEPLOY_FILE" ]; then
+            if ! [ -x "$POSTDEPLOY_FILE" ]; then
+              echo "Error: You do not have permission to execute '$POSTDEPLOY_FILE'. Run:"
+              echo "> chmod +x $POSTDEPLOY_FILE"
+              echo "and commit your changes"
+              exit 1
+            else
+              $POSTDEPLOY_FILE
+            fi
+          fi
+
       - name: Run fixture tests
         run: |
           if [ -f ./scripts/exec_test.sh ]; then
diff --git a/.gitlab/ci_cd.yaml b/.gitlab/ci_cd.yaml
--- a/.gitlab/ci_cd.yaml
+++ b/.gitlab/ci_cd.yaml
@@ -141,15 +141,15 @@ variables:
 
     # Custom test data operations
     - |
-      DATAOPS_FILE=./deploy/${VERSION}/dataops.sh
-      if [ -f "$DATAOPS_FILE" ]; then
-        if ! [ -x "$DATAOPS_FILE" ]; then
-          echo "Error: You do not have permission to execute '$DATAOPS_FILE'. Run:"
-          echo "> chmod +x $DATAOPS_FILE"
+      POSTDEPLOY_FILE=./deploy/${VERSION}/postdeploy.sh
+      if [ -f "$POSTDEPLOY_FILE" ]; then
+        if ! [ -x "$POSTDEPLOY_FILE" ]; then
+          echo "Error: You do not have permission to execute '$POSTDEPLOY_FILE'. Run:"
+          echo "> chmod +x $POSTDEPLOY_FILE"
           echo "and commit your changes"
           exit 1
         else
-          $DATAOPS_FILE
+          $POSTDEPLOY_FILE
         fi
       fi
 
