split jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,7 +21,8 @@ on:
         required: true
 
 jobs:
-  ci_branching:
+  environment:
+    name: Create CI Environment
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -61,7 +62,7 @@ jobs:
           fi
 
       - name: Tinybird version
-        run: tb --version       
+        run: tb --version
 
       - name: Check all the data files syntax
         run: tb check  
@@ -93,33 +94,133 @@ jobs:
           env create tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }} \
           ${_ENV_FLAGS}
 
+  deploy:
+    name: Deploy to CI Environment
+    runs-on: ubuntu-latest
+    needs:
+      - environment
+    defaults:
+      run:
+        working-directory: ${{ inputs.data_project_dir }}
+    if: ${{ github.event.action != 'closed' }}
+    steps:
+      - uses: actions/checkout@master
+        with:
+          fetch-depth: 300
+          ref: ${{ github.event.pull_request.head.sha }}
+      - uses: actions/setup-python@v3
+        with:
+          python-version: "3.11"
+          architecture: "x64"
+
+      - name: Validate input
+        run: |
+          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }
+      - name: Set environment variables
+        run: |
+          _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
+          _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
+          GIT_BRANCH=${GITHUB_HEAD_REF}
+          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
+          echo "_ENV_FLAGS=$_ENV_FLAGS" >> $GITHUB_ENV
+          echo "_NORMALIZED_ENV_NAME=$_NORMALIZED_ENV_NAME" >> $GITHUB_ENV
+          cat .tinyenv >> $GITHUB_ENV
+          echo >> $GITHUB_ENV # Ensures new line at the end of the file
+      - name: Install Tinybird CLI
+        run: |
+          if [ -f "requirements.txt" ]; then
+            pip install -r requirements.txt
+          else
+            pip install tinybird-cli
+          fi
+      - name: Tinybird version
+        run: tb --version
+
+      - name: Check auth
+        run: tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} auth info
+
+      - name: Use Environment
+        run: |
+          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"
+          tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env use $ENVIRONMENT_NAME
+
       - name: Deploy changes to the test Environment
         run: |
             source .tinyenv
-            CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
-            if [ ! -f "$CI_DEPLOY_FILE" ]; then
+            DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+            if [ ! -f "$DEPLOY_FILE" ]; then
               if ${{ inputs.tb_deploy }}; then
-                tb --semver ${VERSION} deploy --fixtures --populate --wait --v3 ${CI_FLAGS}
+                tb --semver ${VERSION} deploy --v3 ${CI_FLAGS}
                 tb release ls
               else
                 tb deploy --populate --fixtures --wait
               fi
             fi
 
-      - name: Custom deployment to the test Environment
+      - name: Custom deployment to the CI Environment
         run: |
             source .tinyenv
-            CI_DEPLOY_FILE=./deploy/${VERSION}/ci-deploy.sh
-            if [ -f "$CI_DEPLOY_FILE" ]; then
-              if ! [ -x "$CI_DEPLOY_FILE" ]; then
-                echo "Error: You do not have permission to execute '$CI_DEPLOY_FILE'. Run:"
-                echo "> chmod +x $CI_DEPLOY_FILE"
+            DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+            if [ -f "$DEPLOY_FILE" ]; then
+              if ! [ -x "$DEPLOY_FILE" ]; then
+                echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
+                echo "> chmod +x $DEPLOY_FILE"
                 echo "and commit your changes"
                 exit 1
               else
-                $CI_DEPLOY_FILE
+                $DEPLOY_FILE
               fi
             fi
+
+  test:
+    name: Run tests
+    runs-on: ubuntu-latest
+    needs:
+      - deploy
+    defaults:
+      run:
+        working-directory: ${{ inputs.data_project_dir }}
+    if: ${{ github.event.action != 'closed' }}
+    steps:
+      - uses: actions/checkout@master
+        with:
+          fetch-depth: 300
+          ref: ${{ github.event.pull_request.head.sha }}
+      - uses: actions/setup-python@v3
+        with:
+          python-version: "3.11"
+          architecture: "x64"
+
+      - name: Validate input
+        run: |
+          [[ "${{ secrets.tb_admin_token }}" ]] || { echo "Go to the tokens section in your Workspace, copy the 'admin token (user@domain.com)' associated to a user account and set TB_ADMIN_TOKEN as a Secret in your Git repository"; exit 1; }
+      - name: Set environment variables
+        run: |
+          _ENV_FLAGS="${ENV_FLAGS:=--last-partition --wait}"
+          _NORMALIZED_ENV_NAME=$(echo $DATA_PROJECT_DIR | rev | cut -d "/" -f 1 | rev | tr '.-' '_')
+          GIT_BRANCH=${GITHUB_HEAD_REF}
+          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
+          echo "_ENV_FLAGS=$_ENV_FLAGS" >> $GITHUB_ENV
+          echo "_NORMALIZED_ENV_NAME=$_NORMALIZED_ENV_NAME" >> $GITHUB_ENV
+          cat .tinyenv >> $GITHUB_ENV
+          echo >> $GITHUB_ENV # Ensures new line at the end of the file
+      - name: Install Tinybird CLI
+        run: |
+          if [ -f "requirements.txt" ]; then
+            pip install -r requirements.txt
+          else
+            pip install tinybird-cli
+          fi
+      - name: Tinybird version
+        run: tb --version
+
+      - name: Check auth
+        run: tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} auth info
+
+      - name: Use Environment
+        run: |
+          ENVIRONMENT_NAME="tmp_ci_${_NORMALIZED_ENV_NAME}_${{ github.event.pull_request.number }}"
+          tb --host ${{ secrets.tb_host }} --token ${{ secrets.tb_admin_token }} env use $ENVIRONMENT_NAME
 
       - name: Run fixture tests
         run: |
@@ -155,6 +256,7 @@ jobs:
               echo "Config file not found at '${CONFIG_FILE}', running with default values"
               ${BASE_CMD} coverage --wait ${LABELS_CMD}
           fi
+
   cleanup:
     runs-on: ubuntu-latest
     defaults:
